// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team3620.robot.subsystems;


import edu.wpi.first.wpilibj.command.Subsystem;

import org.slf4j.Logger;
import org.usfirst.frc.team3620.robot.RobotMap;
import org.usfirst.frc.team3620.robot.commands.TeleOpDriveCommand;
import org.usfirst.frc3620.logger.EventLogging;
import org.usfirst.frc3620.logger.EventLogging.Level;

import com.ctre.phoenix.ErrorCode;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import com.kauailabs.navx.frc.AHRS;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveSubsystem extends Subsystem {
	Logger logger = EventLogging.getLogger(getClass(), Level.INFO);
	public AHRS ahrs = null /* will set in the constructor */;

    private final DifferentialDrive pWMDifferentialDrive = RobotMap.driveSubsystemPWMDifferentialDrive;
    
    private final WPI_TalonSRX driveSubsystemTalonLeft1 = RobotMap.driveSubsystemTalonLeft1;
    private final WPI_VictorSPX driveSubsystemVictorLeft2 = RobotMap.driveSubsystemVictorLeft2;
    private final WPI_VictorSPX driveSubsystemVictorLeft3 = RobotMap.driveSubsystemVictorLeft3;
    private final WPI_VictorSPX driveSubsystemVictorLeft4 = RobotMap.driveSubsystemVictorLeft4;
   
    private final WPI_TalonSRX driveSubsystemTalonRight1 = RobotMap.driveSubsystemTalonRight1;
    private final WPI_VictorSPX driveSubsystemVictorRight2 = RobotMap.driveSubsystemVictorRight2;
    private final WPI_VictorSPX driveSubsystemVictorRight3 = RobotMap.driveSubsystemVictorRight3;
    private final WPI_VictorSPX driveSubsystemVictorRight4 = RobotMap.driveSubsystemVictorRight4;
    
    private final DifferentialDrive cANDifferentialDrive = RobotMap.driveSubsystemCANDifferentialDrive;
    
    private boolean reverse;
	private boolean highGear;//for the motors
	private boolean practice = false;//Use PWM channels on mule board(true) OR use canTalons on comp. bot.(false)
	
	private double turnReducer = 0.9;
    
	public DriveSubsystem() {
		super();               
		if(driveSubsystemTalonLeft1 == null) {
			practice = true;
		}
		ahrs = new AHRS(edu.wpi.first.wpilibj.SPI.Port.kMXP);
		ahrs.enableLogging(false);
	}
	
	@Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    	setDefaultCommand(new TeleOpDriveCommand());
    }

	public void useWPMdrive() {
		practice = true;
	}
	
	public void useCANdrive() {
		practice = false;
	}
	
	private double lowerLimit(double value, double lowerLimit) {//This function removes low input values to insure low voltage don't fidget the motors
		if(Math.abs(value)<=lowerLimit) {
			return(0.0);
		}
		return(value);
	}
	
	private double getSpeedModifier() {
		//return reverse ? -1 : 1;//this will return 1 if reverse is false, and -1 if reverse is true.
		return 1;
	}
	
	public void teleOpDrive(double speed,double turn) {
		speed=lowerLimit(speed, 0.2)*getSpeedModifier();
		turn=lowerLimit(turn, 0.1)*getSpeedModifier();
		double r2 = turn * turn * turnReducer;
		if (turn < 0) {
			r2 = -r2;
		}
		if(practice) {
			pWMDifferentialDrive.arcadeDrive(-speed, r2, true);
		} else {
			pWMDifferentialDrive.stopMotor();
			cANDifferentialDrive.arcadeDrive(-speed, r2, true);
		}
	}

	public void autoDrive(double speed,double turn) {
		if(practice) {
			pWMDifferentialDrive.arcadeDrive(speed, turn);
		} else {
			pWMDifferentialDrive.stopMotor();
			cANDifferentialDrive.arcadeDrive(speed, turn);
		}
	}
	
	public void autoDriveTank(double left, double right) {
		left *= getSpeedModifier();
		right *= getSpeedModifier();
		if(practice) {
			pWMDifferentialDrive.tankDrive(left, right, false);
		}
		else {
			pWMDifferentialDrive.stopMotor();
			cANDifferentialDrive.tankDrive(left, right, false);
		}
	}
	
	public void autoDriveNoSquared(double speed,double turn) {
		if(practice) {
			pWMDifferentialDrive.arcadeDrive(speed, turn, false);
		} else {
			pWMDifferentialDrive.stopMotor();
			cANDifferentialDrive.arcadeDrive(speed, turn, false);
		}
	}
	
	public void setReverseFlag(Boolean setVal) {
		reverse = setVal;
	}
	
	public void resetReverseFlag() {
		setReverseFlag(false);
	}
	
	public void toggleReverseFlag() {
		setReverseFlag(!(reverse));
	}
	
	//Encoders and NavX:
	public void resetEncoders() {
		if (driveSubsystemTalonLeft1 != null) {
		   ErrorCode ec = driveSubsystemTalonLeft1.getSensorCollection().setQuadraturePosition(0, 100);  //10ms timeout for confirmation. reduce this?
		   //ErrorCode ec = RobotMap.driveSubsystemLeftEncoder.getRaw();
		    logger.info("Left encoder reset status = {}", ec);
		}
		if (driveSubsystemTalonRight1 != null) {
			ErrorCode ec = driveSubsystemTalonRight1.getSensorCollection().setQuadraturePosition(0, 100);  //10ms timeout for confirmation. reduce this?
		    logger.info("Right encoder reset status = {}", ec);
		}
		RobotMap.driveSubsystemLeftEncoder.reset();
		RobotMap.driveSubsystemRightEncoder.reset();
	}
	
	public int readLeftEncRaw() {
		if (driveSubsystemTalonLeft1 != null) {
		    //return -1 * driveSubsystemTalonLeft1.getSensorCollection().getQuadraturePosition();
		    return RobotMap.driveSubsystemLeftEncoder.getRaw();
		}
		else {
			return 0;
		}
	}
    
	public int readRightEncRaw() {
		if (driveSubsystemTalonRight1 != null) {
		    //return driveSubsystemTalonRight1.getSensorCollection().getQuadraturePosition();
		    return RobotMap.driveSubsystemRightEncoder.getRaw();
		}
		else {
			return 0;
		}
	}
	
    public void resetNavX() {
		if (ahrs != null) {
			ahrs.resetDisplacement();
			logger.info("Resetting X Displacement, X = {}",
					ahrs.getDisplacementX());
			ahrs.reset();
			logger.info("Resetting NavX Angle, Angle = {}", ahrs.getAngle());
		}
	}
	
    boolean complainedAboutMissingAhrs = false;
    
    public boolean ahrsIsConnected() {
		return ahrs != null && ahrs.isConnected();
	}

	void complainAboutMissingAhrs() {
		if (!complainedAboutMissingAhrs) {
			logger.warn("Cannot read NavX, not connected");
		}
		complainedAboutMissingAhrs = true;
	}

	public double getPitch() {
		if (ahrsIsConnected()) {
			return ahrs.getPitch();
		} else {
			complainAboutMissingAhrs();
			return 0;
		}
	}

	public double getRoll() {
		if (ahrsIsConnected()) {
			return ahrs.getRoll();
		} else {
			complainAboutMissingAhrs();
			return 0;
		}
	}

	public double getAngle() {
		if (ahrsIsConnected()) {
			return ahrs.getAngle(); //Angle direction was opposite of 2017 testing (raw is clockwise-positive, corrected is clockwise-negative)
		} else {
			complainAboutMissingAhrs();
			return 0;
		}
	}

	public double getDisplacementX() {
		if (ahrsIsConnected()) {
			return ahrs.getDisplacementX();
		} else {
			complainAboutMissingAhrs();
			return 0;
		}
	}

	public double getDisplacementY() {
		if (ahrsIsConnected()) {
			return ahrs.getDisplacementY();
		} else {
			complainAboutMissingAhrs();
			return 0;
		}
	}

	public double getDisplacementZ() {
		if (ahrsIsConnected()) {
			return ahrs.getDisplacementZ();
		} else {
			complainAboutMissingAhrs();
			return 0;
		}
	}
	
	public void setMotors(double speedLeft, double speedRight) {
    	cANDifferentialDrive.tankDrive(speedLeft, speedRight);
    }
	
//	public double readLeftEncoder() {
//	return 0.0;
//	}
//	
//	public double readRightEncoder() {
//		return 0.0;
//		}
	
	public void setHighGear() {//@Doug, HoW DOOOooOOOoOooOooOooOOOOOooOOoOooOo??????????????/????//??/??/?????/?
		highGear = true;
	}
	
    public void setLowGear() {
    	highGear = false;
    }
    

    @Override
    public void periodic() {
    	
        SmartDashboard.putNumber("Current Draw on Left Talon 1: ", driveSubsystemTalonLeft1.getOutputCurrent());
        SmartDashboard.putNumber("Current Draw on Left Victor 2: ", driveSubsystemVictorLeft2.getOutputCurrent());
        SmartDashboard.putNumber("Current Draw on Left Victor 3: ", driveSubsystemVictorLeft3.getOutputCurrent());
        SmartDashboard.putNumber("Current Draw on Left Victor 4: ", driveSubsystemVictorLeft4.getOutputCurrent());
        
        SmartDashboard.putNumber("Current Draw on Right Talon 1: ", driveSubsystemTalonRight1.getOutputCurrent());
        SmartDashboard.putNumber("Current Draw on Right Victor 2: ", driveSubsystemVictorRight2.getOutputCurrent());
        SmartDashboard.putNumber("Current Draw on Right Victor 3: ", driveSubsystemVictorRight3.getOutputCurrent());
        SmartDashboard.putNumber("Current Draw on Right Victor 4: ", driveSubsystemVictorRight4.getOutputCurrent());
    }
    

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}