// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.FRC3620_2018_CoffeePi_RobotBuilder.subsystems;

import org.usfirst.frc3620.FRC3620_2018_CoffeePi_RobotBuilder.RobotMap;
import org.usfirst.frc3620.FRC3620_2018_CoffeePi_RobotBuilder.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveSubsystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftSpeedController = RobotMap.driveSubsystemLeftSpeedController;
    private final SpeedController rightSpeedController = RobotMap.driveSubsystemRightSpeedController;
    private final DifferentialDrive pWMDifferentialDrive = RobotMap.driveSubsystemPWMDifferentialDrive;
    private final WPI_TalonSRX talonSRX1 = RobotMap.driveSubsystemTalonSRX1;
    private final WPI_VictorSPX victorSPX2 = RobotMap.driveSubsystemVictorSPX2;
    private final WPI_VictorSPX victorSPX3 = RobotMap.driveSubsystemVictorSPX3;
    private final SpeedControllerGroup leftSpeedControllerGroup = RobotMap.driveSubsystemLeftSpeedControllerGroup;
    private final WPI_TalonSRX talonSRX4 = RobotMap.driveSubsystemTalonSRX4;
    private final WPI_VictorSPX victorSPX5 = RobotMap.driveSubsystemVictorSPX5;
    private final WPI_VictorSPX victorSPX6 = RobotMap.driveSubsystemVictorSPX6;
    private final SpeedControllerGroup rightSpeedControllerGroup = RobotMap.driveSubsystemRightSpeedControllerGroup;
    private final DifferentialDrive cANDifferentialDrive = RobotMap.driveSubsystemCANDifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

